//! Wire protocol types for dogel.bin.
//!
//! This crate owns serializable message shapes that cross process or network
//! boundaries. It deliberately contains no private keys and no transport logic.
//! That keeps protocol evolution separate from libp2p and local storage.

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Current dogel application protocol version.
///
/// Phase 12 treats mismatches as hard failures instead of best-effort
/// compatibility. The field is still named `version` on existing wire structs
/// to avoid a broad rename in the skeleton.
pub const PROTOCOL_VERSION: u32 = 1;

/// Plain chat message before room encryption.
///
/// This struct is serialized and then encrypted with the room key. Receivers
/// must verify that `room_id` matches the outer envelope room id after
/// decryption. Keeping it inside the ciphertext prevents simple envelope
/// rewriting bugs from silently moving plaintext between rooms.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlainMessage {
    /// Random per-message identifier generated by the sender.
    ///
    /// Receivers keep a small in-memory replay cache per room. If the same
    /// `sender_peer_id + message_id` appears again, the envelope is rejected
    /// even if the Ed25519 signature and AEAD tag are valid.
    pub message_id: String,
    pub room_id: String,
    pub body: String,
    pub timestamp_ms: u64,
}

/// Signed encrypted message envelope sent over libp2p.
///
/// `room_id` is intentionally outside ciphertext in v0.1 because the receiver
/// needs it to find the local room key. This leaks room identifiers to peers
/// that receive the envelope. Later versions can replace this with encrypted or
/// hashed room identifiers.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignedEncryptedEnvelope {
    pub version: u32,
    pub room_id: String,
    pub sender_alias: String,
    pub sender_peer_id: String,
    pub sender_signing_public_key_b64: String,
    pub timestamp_ms: u64,
    pub nonce_b64: String,
    pub ciphertext_b64: String,
    pub signature_b64: String,
}

/// Online room invite sent over the already-secured libp2p Noise channel.
///
/// Phase 10 intentionally keeps invites online-only: both peers must be
/// connected. The room key is present in this request payload, so it relies on
/// the direct libp2p secure channel for confidentiality. This is still a
/// meaningful UX/security improvement over manually sharing a weak room secret,
/// but it is not an offline X25519 invite format yet.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RoomInvite {
    pub version: u32,
    pub invite_id: String,
    pub room_id: String,
    /// Random room seed for Phase 12 invite-created rooms.
    ///
    /// Receivers do not use this directly as the AEAD key. They derive the room
    /// key from this seed plus the signed room membership state.
    pub room_key_b64: String,
    pub ephemeral: bool,
    pub membership: RoomMembershipState,
    pub sender_alias: String,
    pub sender_peer_id: String,
    pub sender_signing_public_key_b64: String,
    pub timestamp_ms: u64,
    pub signature_b64: String,
}

/// Discoverable peer metadata published to a bootstrap / directory node.
///
/// The peer advertisement is intentionally lightweight and memory-only in this
/// phase. A bootstrap node stores it in RAM and returns it to resolving peers.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct PeerAdvertisement {
    pub peer_id: String,
    pub alias: Option<String>,
    pub direct_addrs: Vec<String>,
    pub relayed_addrs: Vec<String>,
    pub nat_status: String,
    pub observed_at_ms: u64,
    pub expires_at_ms: u64,
}

/// Creator-signed room membership state.
///
/// The peer list must be sorted before signing. The signature covers the room
/// id, creator identity, protocol version and exact peer set, which makes room
/// key derivation bind to the same state that users accept through invites.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RoomMembershipState {
    pub version: u32,
    pub room_id: String,
    pub creator_peer_id: String,
    pub creator_signing_public_key_b64: String,
    pub peers: Vec<String>,
    pub membership_signature_b64: String,
}

/// Request sent through the libp2p request-response protocol.
///
/// We use an enum so Phase 10 can carry both encrypted chat envelopes and online
/// room invites over the same `/dogel/message/1` stream protocol.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "payload")]
pub enum DogelRequest {
    Envelope(SignedEncryptedEnvelope),
    Invite(RoomInvite),
}

/// Discovery requests exchanged with the bootstrap / directory peer.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "payload")]
pub enum DiscoveryRequest {
    RegisterPeer(PeerAdvertisement),
    ResolvePeer { query: String },
    ListPeers,
}

/// Discovery responses returned by the bootstrap / directory peer.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "payload")]
pub enum DiscoveryResponse {
    Ack {
        ok: bool,
        error: Option<String>,
    },
    ResolvePeerResponse {
        found: bool,
        advertisement: Option<PeerAdvertisement>,
        reason: Option<String>,
    },
    ListPeersResponse {
        peers: Vec<PeerAdvertisement>,
    },
}

/// Response to a dogel request.
///
/// Chat messages and invites are semantically one-way, but request-response
/// needs a small reply so the stream can close cleanly and debugging is easier.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DogelResponse {
    pub ok: bool,
    pub error: Option<String>,
}

impl DogelResponse {
    pub fn ok() -> Self {
        Self {
            ok: true,
            error: None,
        }
    }

    pub fn error(message: impl Into<String>) -> Self {
        Self {
            ok: false,
            error: Some(message.into()),
        }
    }
}

/// Stable payload that is signed with Ed25519.
///
/// The signature must cover every security-relevant envelope field except the
/// signature itself. This prevents an attacker from changing room id, sender
/// metadata, nonce or ciphertext without invalidating the signature.
#[derive(Debug, Clone, Serialize)]
struct EnvelopeSigningPayload<'a> {
    version: u32,
    room_id: &'a str,
    sender_alias: &'a str,
    sender_peer_id: &'a str,
    sender_signing_public_key_b64: &'a str,
    timestamp_ms: u64,
    nonce_b64: &'a str,
    ciphertext_b64: &'a str,
}

/// Stable payload signed for online room invites.
///
/// The signature covers the room key because otherwise a malicious modified
/// client on the same transport path could rewrite the key while preserving the
/// surrounding metadata. The transport provides confidentiality; the signature
/// provides application-level authenticity.
#[derive(Debug, Clone, Serialize)]
struct InviteSigningPayload<'a> {
    version: u32,
    invite_id: &'a str,
    room_id: &'a str,
    room_key_b64: &'a str,
    ephemeral: bool,
    membership: &'a RoomMembershipState,
    sender_alias: &'a str,
    sender_peer_id: &'a str,
    sender_signing_public_key_b64: &'a str,
    timestamp_ms: u64,
}

/// Stable payload signed by the room creator for membership state.
#[derive(Debug, Clone, Serialize)]
struct MembershipSigningPayload<'a> {
    version: u32,
    room_id: &'a str,
    creator_peer_id: &'a str,
    creator_signing_public_key_b64: &'a str,
    peers: &'a [String],
}

#[derive(Debug, Error)]
pub enum ProtocolError {
    #[error("failed to serialize signing payload: {0}")]
    SigningPayloadSerialize(serde_json::Error),

    #[error("protocol version mismatch: expected {expected}, got {actual}")]
    VersionMismatch { expected: u32, actual: u32 },
}

/// Hard-reject any wire object that does not use the current protocol version.
pub fn require_protocol_version(actual: u32) -> Result<(), ProtocolError> {
    if actual == PROTOCOL_VERSION {
        Ok(())
    } else {
        Err(ProtocolError::VersionMismatch {
            expected: PROTOCOL_VERSION,
            actual,
        })
    }
}

impl SignedEncryptedEnvelope {
    /// Serialize the exact bytes that must be signed or verified.
    ///
    /// We use JSON for v0.1 because it is transparent and debuggable. This is
    /// not the most compact representation, but compactness is not the current
    /// bottleneck. Later we can move to postcard/bincode if we version the
    /// payload carefully.
    pub fn signing_payload(&self) -> Result<Vec<u8>, ProtocolError> {
        let payload = EnvelopeSigningPayload {
            version: self.version,
            room_id: &self.room_id,
            sender_alias: &self.sender_alias,
            sender_peer_id: &self.sender_peer_id,
            sender_signing_public_key_b64: &self.sender_signing_public_key_b64,
            timestamp_ms: self.timestamp_ms,
            nonce_b64: &self.nonce_b64,
            ciphertext_b64: &self.ciphertext_b64,
        };

        serde_json::to_vec(&payload).map_err(ProtocolError::SigningPayloadSerialize)
    }
}

impl RoomInvite {
    /// Serialize the exact bytes that must be signed or verified for an invite.
    pub fn signing_payload(&self) -> Result<Vec<u8>, ProtocolError> {
        let payload = InviteSigningPayload {
            version: self.version,
            invite_id: &self.invite_id,
            room_id: &self.room_id,
            room_key_b64: &self.room_key_b64,
            ephemeral: self.ephemeral,
            membership: &self.membership,
            sender_alias: &self.sender_alias,
            sender_peer_id: &self.sender_peer_id,
            sender_signing_public_key_b64: &self.sender_signing_public_key_b64,
            timestamp_ms: self.timestamp_ms,
        };

        serde_json::to_vec(&payload).map_err(ProtocolError::SigningPayloadSerialize)
    }
}

impl RoomMembershipState {
    /// Serialize the exact bytes the room creator signs for membership.
    pub fn signing_payload(&self) -> Result<Vec<u8>, ProtocolError> {
        let payload = MembershipSigningPayload {
            version: self.version,
            room_id: &self.room_id,
            creator_peer_id: &self.creator_peer_id,
            creator_signing_public_key_b64: &self.creator_signing_public_key_b64,
            peers: &self.peers,
        };

        serde_json::to_vec(&payload).map_err(ProtocolError::SigningPayloadSerialize)
    }
}

/// Return a sorted and deduplicated copy of peer ids for canonical membership.
pub fn canonical_peer_list(peers: impl IntoIterator<Item = String>) -> Vec<String> {
    let mut peers: Vec<_> = peers.into_iter().collect();
    peers.sort();
    peers.dedup();
    peers
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn canonical_peer_list_sorts_and_deduplicates() {
        let peers = canonical_peer_list([
            "peer-c".to_string(),
            "peer-a".to_string(),
            "peer-c".to_string(),
            "peer-b".to_string(),
        ]);

        assert_eq!(peers, ["peer-a", "peer-b", "peer-c"]);
    }

    #[test]
    fn membership_payload_changes_when_peer_set_changes() {
        let one = RoomMembershipState {
            version: PROTOCOL_VERSION,
            room_id: "room".to_string(),
            creator_peer_id: "creator".to_string(),
            creator_signing_public_key_b64: "key".to_string(),
            peers: canonical_peer_list(["a".to_string(), "b".to_string()]),
            membership_signature_b64: String::new(),
        };
        let mut two = one.clone();
        two.peers = canonical_peer_list(["a".to_string(), "b".to_string(), "c".to_string()]);

        assert_ne!(
            one.signing_payload().unwrap(),
            two.signing_payload().unwrap()
        );
    }

    #[test]
    fn protocol_version_mismatch_is_rejected() {
        assert!(require_protocol_version(PROTOCOL_VERSION).is_ok());
        assert!(matches!(
            require_protocol_version(PROTOCOL_VERSION + 1),
            Err(ProtocolError::VersionMismatch { .. })
        ));
    }
}
