//! Wire protocol types for dogel.bin.
//!
//! This crate owns serializable message shapes that cross process or network
//! boundaries. It deliberately contains no private keys and no transport logic.
//! That keeps protocol evolution separate from libp2p and local storage.

use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Plain chat message before room encryption.
///
/// This struct is serialized and then encrypted with the room key. Receivers
/// must verify that `room_id` matches the outer envelope room id after
/// decryption. Keeping it inside the ciphertext prevents simple envelope
/// rewriting bugs from silently moving plaintext between rooms.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlainMessage {
    /// Random per-message identifier generated by the sender.
    ///
    /// Receivers keep a small in-memory replay cache per room. If the same
    /// `sender_peer_id + message_id` appears again, the envelope is rejected
    /// even if the Ed25519 signature and AEAD tag are valid.
    pub message_id: String,
    pub room_id: String,
    pub body: String,
    pub timestamp_ms: u64,
}

/// Signed encrypted message envelope sent over libp2p.
///
/// `room_id` is intentionally outside ciphertext in v0.1 because the receiver
/// needs it to find the local room key. This leaks room identifiers to peers
/// that receive the envelope. Later versions can replace this with encrypted or
/// hashed room identifiers.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignedEncryptedEnvelope {
    pub version: u32,
    pub room_id: String,
    pub sender_alias: String,
    pub sender_peer_id: String,
    pub sender_signing_public_key_b64: String,
    pub timestamp_ms: u64,
    pub nonce_b64: String,
    pub ciphertext_b64: String,
    pub signature_b64: String,
}

/// Online room invite sent over the already-secured libp2p Noise channel.
///
/// Phase 10 intentionally keeps invites online-only: both peers must be
/// connected. The room key is present in this request payload, so it relies on
/// the direct libp2p secure channel for confidentiality. This is still a
/// meaningful UX/security improvement over manually sharing a weak room secret,
/// but it is not an offline X25519 invite format yet.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RoomInvite {
    pub version: u32,
    pub invite_id: String,
    pub room_id: String,
    pub room_key_b64: String,
    pub ephemeral: bool,
    pub sender_alias: String,
    pub sender_peer_id: String,
    pub sender_signing_public_key_b64: String,
    pub timestamp_ms: u64,
    pub signature_b64: String,
}

/// Request sent through the libp2p request-response protocol.
///
/// We use an enum so Phase 10 can carry both encrypted chat envelopes and online
/// room invites over the same `/dogel/message/1` stream protocol.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "payload")]
pub enum DogelRequest {
    Envelope(SignedEncryptedEnvelope),
    Invite(RoomInvite),
}

/// Response to a dogel request.
///
/// Chat messages and invites are semantically one-way, but request-response
/// needs a small reply so the stream can close cleanly and debugging is easier.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DogelResponse {
    pub ok: bool,
    pub error: Option<String>,
}

impl DogelResponse {
    pub fn ok() -> Self {
        Self {
            ok: true,
            error: None,
        }
    }

    pub fn error(message: impl Into<String>) -> Self {
        Self {
            ok: false,
            error: Some(message.into()),
        }
    }
}

/// Stable payload that is signed with Ed25519.
///
/// The signature must cover every security-relevant envelope field except the
/// signature itself. This prevents an attacker from changing room id, sender
/// metadata, nonce or ciphertext without invalidating the signature.
#[derive(Debug, Clone, Serialize)]
struct EnvelopeSigningPayload<'a> {
    version: u32,
    room_id: &'a str,
    sender_alias: &'a str,
    sender_peer_id: &'a str,
    sender_signing_public_key_b64: &'a str,
    timestamp_ms: u64,
    nonce_b64: &'a str,
    ciphertext_b64: &'a str,
}

/// Stable payload signed for online room invites.
///
/// The signature covers the room key because otherwise a malicious modified
/// client on the same transport path could rewrite the key while preserving the
/// surrounding metadata. The transport provides confidentiality; the signature
/// provides application-level authenticity.
#[derive(Debug, Clone, Serialize)]
struct InviteSigningPayload<'a> {
    version: u32,
    invite_id: &'a str,
    room_id: &'a str,
    room_key_b64: &'a str,
    ephemeral: bool,
    sender_alias: &'a str,
    sender_peer_id: &'a str,
    sender_signing_public_key_b64: &'a str,
    timestamp_ms: u64,
}

#[derive(Debug, Error)]
pub enum ProtocolError {
    #[error("failed to serialize signing payload: {0}")]
    SigningPayloadSerialize(serde_json::Error),
}

impl SignedEncryptedEnvelope {
    /// Serialize the exact bytes that must be signed or verified.
    ///
    /// We use JSON for v0.1 because it is transparent and debuggable. This is
    /// not the most compact representation, but compactness is not the current
    /// bottleneck. Later we can move to postcard/bincode if we version the
    /// payload carefully.
    pub fn signing_payload(&self) -> Result<Vec<u8>, ProtocolError> {
        let payload = EnvelopeSigningPayload {
            version: self.version,
            room_id: &self.room_id,
            sender_alias: &self.sender_alias,
            sender_peer_id: &self.sender_peer_id,
            sender_signing_public_key_b64: &self.sender_signing_public_key_b64,
            timestamp_ms: self.timestamp_ms,
            nonce_b64: &self.nonce_b64,
            ciphertext_b64: &self.ciphertext_b64,
        };

        serde_json::to_vec(&payload).map_err(ProtocolError::SigningPayloadSerialize)
    }
}

impl RoomInvite {
    /// Serialize the exact bytes that must be signed or verified for an invite.
    pub fn signing_payload(&self) -> Result<Vec<u8>, ProtocolError> {
        let payload = InviteSigningPayload {
            version: self.version,
            invite_id: &self.invite_id,
            room_id: &self.room_id,
            room_key_b64: &self.room_key_b64,
            ephemeral: self.ephemeral,
            sender_alias: &self.sender_alias,
            sender_peer_id: &self.sender_peer_id,
            sender_signing_public_key_b64: &self.sender_signing_public_key_b64,
            timestamp_ms: self.timestamp_ms,
        };

        serde_json::to_vec(&payload).map_err(ProtocolError::SigningPayloadSerialize)
    }
}
